services:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - wpdb:/var/lib/mysql
    env_file:
      - .env
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    networks:
      - wpmari_net
    ports: 
      - 3307:3306
    container_name: ${APP_NAME:-wpmari}_db_container

  web:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
      target: wp-cli
    depends_on: 
      - mariadb
    restart: unless-stopped
    volumes: 
      - ./src/:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    networks:
      - wpmari_net
    ports: 
      - 8080:80
    user: "${UID}:${GID}"
    container_name: ${APP_NAME:-wpmari}_wp_container

  adminer:
    image: adminer:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
    - wpmari_net
    ports:
      - 8082:8080
    container_name: ${APP_NAME:-wpmari}_adminer_container

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - wpmari_net
    ports:
      - "8081:80"
    container_name: ${APP_NAME:-wpmari}_phpmyadmin_container

networks:
  wpmari_net:
volumes:
  wpdb: